/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

/**
 *
 * @author ASUS
 */
public class F1 extends javax.swing.JFrame {
    
    
    /**
     * Creates new form F1
     */
    public F1() {
        initComponents();
        setSize(522, 555);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        F1Icon2 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        F1Icon1 = new javax.swing.JTextField();
        F1Player1Name = new javax.swing.JTextField();
        F1Player2Name = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        NoticeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Made by Nayeem Hossain", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 24), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton1.setText("Player 2");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jButton1);
        jButton1.setBounds(260, 60, 120, 30);

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton2.setText("Name:");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 100, 65, 30);

        jButton6.setBackground(new java.awt.Color(247, 7, 7));
        jButton6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton6.setText("Notice:");
        jButton6.setBorder(null);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(20, 300, 90, 30);

        jButton7.setBackground(new java.awt.Color(0, 51, 51));
        jButton7.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton7.setText("X/O :");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(260, 140, 65, 30);

        F1Icon2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        F1Icon2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(F1Icon2);
        F1Icon2.setBounds(330, 140, 150, 30);

        jButton9.setBackground(new java.awt.Color(0, 51, 51));
        jButton9.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton9.setText("Name:");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(20, 100, 65, 30);

        jButton10.setBackground(new java.awt.Color(0, 51, 51));
        jButton10.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton10.setText("X/O :");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(20, 140, 55, 30);

        F1Icon1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        F1Icon1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        F1Icon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1Icon1ActionPerformed(evt);
            }
        });
        jPanel1.add(F1Icon1);
        F1Icon1.setBounds(90, 140, 150, 30);

        F1Player1Name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        F1Player1Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        F1Player1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1Player1NameActionPerformed(evt);
            }
        });
        jPanel1.add(F1Player1Name);
        F1Player1Name.setBounds(90, 100, 150, 30);

        F1Player2Name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        F1Player2Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(F1Player2Name);
        F1Player2Name.setBounds(330, 100, 150, 30);

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jButton3.setText("Done");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(260, 180, 220, 50);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jButton4.setText("Done");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 180, 220, 50);

        jButton5.setBackground(new java.awt.Color(51, 204, 255));
        jButton5.setFont(new java.awt.Font("Bauhaus 93", 3, 70)); // NOI18N
        jButton5.setText("Go!");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(30, 350, 440, 140);

        jButton8.setBackground(new java.awt.Color(0, 51, 51));
        jButton8.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton8.setText("Player 1");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(20, 60, 120, 30);

        NoticeTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(NoticeTextField);
        NoticeTextField.setBounds(120, 300, 360, 30);

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Icon must have to be Upper Case");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 250, 450, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        PlayerTwoName=F1Player2Name.getText();
        PlayerTwoIcon=F1Icon2.getText();
        if(PlayerTwoName.length()!=0 && PlayerTwoIcon.length()!=0)
        {
            if(Form1Check==0)
            {   
                if(PlayerTwoIcon.contains("X"))
                {
                    F1Icon1.setText("O");
                    NoticeTextField.setText("Done.");
                    Form1Check=1;
                }
                else if(PlayerTwoIcon.contains("O"))
                {
                    F1Icon1.setText("X");
                    NoticeTextField.setText("Done.");
                    Form1Check=1;
                }
                else
                {
                    NoticeTextField.setText("You have Entered wrong icon or lower case icon!");
                }
            }
        }
        else
        {
            if(PlayerTwoName.length()==0 && PlayerTwoIcon.length()==0)
            {
                NoticeTextField.setText("You have missed player 2's name and icon!");
            }
            else
            {
                if(PlayerTwoName.length()==0)
                {
                    NoticeTextField.setText("You have missed player 2's name!");
                }
                if(PlayerTwoIcon.length()==0)
                {
                    NoticeTextField.setText("You have missed player 2's icon!");
                }
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        PlayerOneName=F1Player1Name.getText();
        PlayerOneIcon=F1Icon1.getText();
        if(PlayerOneName.length()!=0 && PlayerOneIcon.length()!=0)
        {
            if(Form1Check==0)
            {   
                if(PlayerOneIcon.contains("X"))
                {
                    F1Icon2.setText("O");
                    NoticeTextField.setText("Done.");
                    Form1Check=1;
                }
                else if(PlayerOneIcon.contains("O"))
                {
                    F1Icon2.setText("X");
                    NoticeTextField.setText("Done.");
                    Form1Check=1;
                }
                else
                {
                    NoticeTextField.setText("You have Entered wrong icon or lower case icon!");
                }
            }
        }
        else
        {
            if(PlayerOneName.length()==0 && PlayerOneIcon.length()==0)
            {
                NoticeTextField.setText("You have missed player 1's name and icon!");
            }
            else
            {
                if(PlayerOneName.length()==0)
                {
                    NoticeTextField.setText("You have missed player 1's name!");
                }
                if(PlayerOneIcon.length()==0)
                {
                    NoticeTextField.setText("You have missed player 1's icon!");
                }
            }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if(PlayerOneName.length()!=0 && PlayerTwoName.length()!=0)
        {
            F2 Object=new F2();
            Object.setVisible(true);
            Object.PlayerOneName=this.PlayerOneName;
            Object.PlayerTwoName=this.PlayerTwoName;
            Object.Icon1=F1Icon1.getText();
            Object.Icon2=F1Icon2.getText();
            Object.F2Player1Name.setText(PlayerOneName);
            Object.F2Player2Name.setText(PlayerTwoName);
            Object.StopWatch();
            setVisible(false);
        }
        else
            NoticeTextField.setText("Please, Fullfill Players name and Icons!");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void F1Icon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1Icon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F1Icon1ActionPerformed

    private void F1Player1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1Player1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F1Player1NameActionPerformed
    
    public String PlayerOneName=new String();
    public String PlayerOneIcon=new String();
    public String PlayerTwoName=new String();
    public String PlayerTwoIcon=new String();
    int Form1Check=0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField F1Icon1;
    private javax.swing.JTextField F1Icon2;
    private javax.swing.JTextField F1Player1Name;
    private javax.swing.JTextField F1Player2Name;
    private javax.swing.JTextField NoticeTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
