/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

/**
 *
 * @author ASUS
 */
public class F2 extends javax.swing.JFrame {
    /*
   String Icon1= new String();
   String Icon2= new String();
   */
    public F2() {
        initComponents();
        setSize(522, 555);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        F2Player2Name = new javax.swing.JTextField();
        F2Player1Name = new javax.swing.JTextField();
        Two = new javax.swing.JButton();
        Three = new javax.swing.JButton();
        Four = new javax.swing.JButton();
        Five = new javax.swing.JButton();
        Six = new javax.swing.JButton();
        Seven = new javax.swing.JButton();
        Eight = new javax.swing.JButton();
        Nine = new javax.swing.JButton();
        One = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ReultField = new javax.swing.JTextField();
        MillisecondP1 = new javax.swing.JTextField();
        SecondP2 = new javax.swing.JTextField();
        MillisecondP2 = new javax.swing.JTextField();
        SecondP1 = new javax.swing.JTextField();
        Restart = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Restart1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Made by Nayeem Hossain", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 24), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(null);

        jLabel1.setText("jLabel1");

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Made by Nayeem Hossain", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 24), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel2.setLayout(null);

        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton6.setText("Player 2");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(260, 380, 120, 30);

        jButton7.setBackground(new java.awt.Color(0, 51, 51));
        jButton7.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton7.setText("Player 1");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(10, 380, 120, 30);

        jButton9.setBackground(new java.awt.Color(0, 51, 51));
        jButton9.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton9.setText("Name:");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(260, 420, 65, 30);

        jButton10.setBackground(new java.awt.Color(0, 51, 51));
        jButton10.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton10.setText("Time:");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(10, 460, 57, 30);

        jButton11.setBackground(new java.awt.Color(0, 51, 51));
        jButton11.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton11.setText("TIME:");
        jButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);
        jButton11.setBounds(260, 460, 57, 30);

        jButton12.setBackground(new java.awt.Color(0, 51, 51));
        jButton12.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton12.setText("Name:");
        jButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);
        jButton12.setBounds(10, 420, 65, 30);

        F2Player2Name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        F2Player2Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F2Player2Name);
        F2Player2Name.setBounds(330, 420, 150, 30);

        F2Player1Name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        F2Player1Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F2Player1Name);
        F2Player1Name.setBounds(80, 420, 150, 30);

        Two.setBackground(new java.awt.Color(153, 255, 255));
        Two.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoActionPerformed(evt);
            }
        });
        jPanel2.add(Two);
        Two.setBounds(210, 40, 70, 60);

        Three.setBackground(new java.awt.Color(153, 255, 255));
        Three.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });
        jPanel2.add(Three);
        Three.setBounds(290, 40, 70, 60);

        Four.setBackground(new java.awt.Color(153, 255, 255));
        Four.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourActionPerformed(evt);
            }
        });
        jPanel2.add(Four);
        Four.setBounds(130, 110, 70, 60);

        Five.setBackground(new java.awt.Color(153, 255, 255));
        Five.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveActionPerformed(evt);
            }
        });
        jPanel2.add(Five);
        Five.setBounds(210, 110, 70, 60);

        Six.setBackground(new java.awt.Color(153, 255, 255));
        Six.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixActionPerformed(evt);
            }
        });
        jPanel2.add(Six);
        Six.setBounds(290, 110, 70, 60);

        Seven.setBackground(new java.awt.Color(153, 255, 255));
        Seven.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenActionPerformed(evt);
            }
        });
        jPanel2.add(Seven);
        Seven.setBounds(130, 180, 70, 60);

        Eight.setBackground(new java.awt.Color(153, 255, 255));
        Eight.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightActionPerformed(evt);
            }
        });
        jPanel2.add(Eight);
        Eight.setBounds(210, 180, 70, 60);

        Nine.setBackground(new java.awt.Color(153, 255, 255));
        Nine.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineActionPerformed(evt);
            }
        });
        jPanel2.add(Nine);
        Nine.setBounds(290, 180, 70, 60);

        One.setBackground(new java.awt.Color(153, 255, 255));
        One.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });
        jPanel2.add(One);
        One.setBounds(130, 40, 70, 60);

        jButton1.setBackground(new java.awt.Color(0, 155, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Result");
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 260, 100, 50);

        ReultField.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel2.add(ReultField);
        ReultField.setBounds(120, 260, 360, 50);

        MillisecondP1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MillisecondP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MillisecondP1.setText("00");
        jPanel2.add(MillisecondP1);
        MillisecondP1.setBounds(160, 460, 70, 30);

        SecondP2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SecondP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SecondP2.setText("00");
        jPanel2.add(SecondP2);
        SecondP2.setBounds(330, 460, 70, 30);

        MillisecondP2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MillisecondP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MillisecondP2.setText("00");
        jPanel2.add(MillisecondP2);
        MillisecondP2.setBounds(410, 460, 70, 30);

        SecondP1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SecondP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SecondP1.setText("00");
        jPanel2.add(SecondP1);
        SecondP1.setBounds(80, 460, 70, 30);

        Restart.setBackground(new java.awt.Color(0, 255, 0));
        Restart.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Restart.setText("Restart");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });
        jPanel2.add(Restart);
        Restart.setBounds(10, 320, 210, 50);

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton3.setText("Stop");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(240, 320, 110, 50);

        Restart1.setBackground(new java.awt.Color(0, 255, 0));
        Restart1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Restart1.setText("Start");
        Restart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restart1ActionPerformed(evt);
            }
        });
        jPanel2.add(Restart1);
        Restart1.setBounds(370, 320, 110, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed
    
    private void Check(int Result[])
    {
        if(Result[0]+Result[1]+Result[2]==3||Result[0]+Result[1]+Result[2]==30)
        {
            if(Result[0]+Result[1]+Result[2]==3)
            {
                //ReultField.setText(PlayerOneName+" has won the match!");
                ReultField.setText(PlayerOneName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
            else
            {
                ReultField.setText(PlayerTwoName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
        }
        else if(Result[3]+Result[4]+Result[5]==3||Result[3]+Result[4]+Result[5]==30)
        {
            if(Result[3]+Result[4]+Result[5]==3)
            {
                ReultField.setText(PlayerOneName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
            else
            {
                ReultField.setText(PlayerTwoName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
        }
        else if(Result[6]+Result[7]+Result[8]==3||Result[6]+Result[7]+Result[8]==30)
        {
            if(Result[6]+Result[7]+Result[8]==3)
            {
                ReultField.setText(PlayerOneName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
            else
            {
                ReultField.setText(PlayerTwoName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
        }
        else if(Result[0]+Result[3]+Result[6]==3||Result[0]+Result[3]+Result[6]==30)
        {
            if(Result[0]+Result[3]+Result[6]==3)
            {
                ReultField.setText(PlayerOneName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
            else
            {
                ReultField.setText(PlayerTwoName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
        }
        else if(Result[1]+Result[4]+Result[7]==3||Result[1]+Result[4]+Result[7]==30)
        {
            if(Result[1]+Result[4]+Result[7]==3)
            {
                ReultField.setText(PlayerOneName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
            else
            {
                ReultField.setText(PlayerTwoName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
        }
        else if(Result[2]+Result[5]+Result[8]==3||Result[2]+Result[5]+Result[8]==30)
        {
            if(Result[2]+Result[5]+Result[8]==3)
            {
                ReultField.setText(PlayerOneName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
            else
            {
                ReultField.setText(PlayerTwoName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
        }
        else if(Result[0]+Result[4]+Result[8]==3||Result[0]+Result[4]+Result[8]==30)
        {
            if(Result[0]+Result[4]+Result[8]==3)
            {
                ReultField.setText(PlayerOneName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
            else
            {
                ReultField.setText(PlayerTwoName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
        }
        else if(Result[2]+Result[4]+Result[6]==3||Result[2]+Result[4]+Result[6]==30)
        {
            if(Result[2]+Result[4]+Result[6]==3)
            {
                ReultField.setText(PlayerOneName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
            else
            {
                ReultField.setText(PlayerTwoName+" has won the match!");
                Disable=1;
                
                // Stopping Time
                State[0]=1;
                State[1]=1;
            }
        }
        else if(Result[0]!=0 && Result[1]!=0 && Result[2]!=0 && Result[3]!=0 && Result[4]!=0 && Result[5]!=0 && Result[6]!=0 && Result[7]!=0 && Result[8]!=0)
        {
            ReultField.setText("Match Drawn!");
            Disable=1;
            
            // Stopping Time
            State[0]=1;
            State[1]=1;
        }
    }
    public void StopWatch()
    {
        Thread t = new Thread()
        {
            public void run()  
            {
                for(;;)
                {
                    if(State[0]==0)
                    {
                        try
                        {
                            sleep(1);
                            if(Milliseconds[0]>1000)
                            {
                                Milliseconds[0]=0;
                                Seconds[0]++;
                            }
                          
                            MillisecondP1.setText(" "+Milliseconds[0]);
                            Milliseconds[0]++;
                            SecondP1.setText(" "+Seconds[0]);
                        }
                        catch(Exception e){}
                    }
                    else
                        break;
                }
            }
        };
        t.start();
        
        Thread t2 = new Thread()
        {
            public void run()  
            {
                for(;;)
                {
                    if(State[1]==0)
                    {
                        try
                        {
                            sleep(1);
                            if(Milliseconds[1]>1000)
                            {
                                Milliseconds[1]=0;
                                Seconds[1]++;
                            }
                            MillisecondP2.setText(" "+Milliseconds[1]);
                            Milliseconds[1]++;
                            SecondP2.setText(" "+Seconds[1]);
                        }
                        catch(Exception e){}
                    }
                    else
                        break;
                }
            }
        };
        t2.start();
    }
    
    private void OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneActionPerformed
        // TODO add your handling code here:
        if(Disable==0)
        {
            int Index=0;
            if(FixTheIcon[Index]==0)
            {
                if(SetIcon%2==0)
                {
                    One.setText(Icon1);
                    Result[Index]=1;
                    SetIcon++;
                    // Time Active Player 1
                    State[0]=1;
                    State[1]=0;
                    StopWatch();
                    //
                    Check(Result);
                }
                else
                {
                    One.setText(Icon2);
                    Result[Index]=10;
                    SetIcon++;
                    // Time Active Player 2
                    State[0]=0;
                    State[1]=1;
                    StopWatch();
                    //
                    Check(Result);
                }
                FixTheIcon[Index]=1;
            }
        }
    }//GEN-LAST:event_OneActionPerformed

    private void TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoActionPerformed
        // TODO add your handling code here:
        if(Disable==0)
        {
            int Index=1;
            if(FixTheIcon[Index]==0)
            {
                if(SetIcon%2==0)
                {
                    Two.setText(Icon1);
                    Result[Index]=1;
                    SetIcon++;
                    // Time Active Player 1
                    State[0]=1;
                    State[1]=0;
                    StopWatch();
                    //
                    Check(Result);
                }
                else
                {
                    Two.setText(Icon2);
                    Result[Index]=10;
                    SetIcon++;
                    // Time Active Player 2
                    State[0]=0;
                    State[1]=1;
                    StopWatch();
                    //
                    Check(Result);
                }
                FixTheIcon[Index]=1;
            }
        }
    }//GEN-LAST:event_TwoActionPerformed

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeActionPerformed
        // TODO add your handling code here:
        if(Disable==0)
        {
            int Index=2;
            if(FixTheIcon[Index]==0)
            {
                if(SetIcon%2==0)
                {
                    Three.setText(Icon1);
                    Result[Index]=1;
                    SetIcon++;
                    // Time Active Player 1
                    State[0]=1;
                    State[1]=0;
                    StopWatch();
                    //
                    Check(Result);
                }
                else
                {
                    Three.setText(Icon2);
                    Result[Index]=10;
                    SetIcon++;
                    // Time Active Player 2
                    State[0]=0;
                    State[1]=1;
                    StopWatch();
                    //
                    Check(Result);
                }
                FixTheIcon[Index]=1;
            }
        }
    }//GEN-LAST:event_ThreeActionPerformed

    private void FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourActionPerformed
        // TODO add your handling code here:
        if(Disable==0)
        {
            int Index=3;
            if(FixTheIcon[Index]==0)
            {
                if(SetIcon%2==0)
                {
                    Four.setText(Icon1);
                    Result[Index]=1;
                    SetIcon++;
                    // Time Active Player 1
                    State[0]=1;
                    State[1]=0;
                    StopWatch();
                    //
                    Check(Result);
                }
                else
                {
                    Four.setText(Icon2);
                    Result[Index]=10;
                    SetIcon++;
                    // Time Active Player 2
                    State[0]=0;
                    State[1]=1;
                    StopWatch();
                    //
                    Check(Result);
                }
                FixTheIcon[Index]=1;
            }
        }
    }//GEN-LAST:event_FourActionPerformed

    private void FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveActionPerformed
        // TODO add your handling code here:
        if(Disable==0)
        {
            int Index=4;
            if(FixTheIcon[Index]==0)
            {
                if(SetIcon%2==0)
                {
                    Five.setText(Icon1);
                    Result[Index]=1;
                    SetIcon++;
                    // Time Active Player 1
                    State[0]=1;
                    State[1]=0;
                    StopWatch();
                    //
                    Check(Result);
                }
                else
                {
                    Five.setText(Icon2);
                    Result[Index]=10;
                    SetIcon++;
                    // Time Active Player 2
                    State[0]=0;
                    State[1]=1;
                    StopWatch();
                    //
                    Check(Result);
                }
                FixTheIcon[Index]=1;
            }
        }
    }//GEN-LAST:event_FiveActionPerformed

    private void SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixActionPerformed
        // TODO add your handling code here:
        if(Disable==0)
        {
            int Index=5;
            if(FixTheIcon[Index]==0)
            {
                if(SetIcon%2==0)
                {
                    Six.setText(Icon1);
                    Result[Index]=1;
                    SetIcon++;
                    // Time Active Player 1
                    State[0]=1;
                    State[1]=0;
                    StopWatch();
                    //
                    Check(Result);
                }
                else
                {
                    Six.setText(Icon2);
                    Result[Index]=10;
                    SetIcon++;
                    // Time Active Player 2
                    State[0]=0;
                    State[1]=1;
                    StopWatch();
                    //
                    Check(Result);
                }
                FixTheIcon[Index]=1;
            }
        }
    }//GEN-LAST:event_SixActionPerformed

    private void SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenActionPerformed
        // TODO add your handling code here:
        if(Disable==0)
        {
            int Index=6;
            if(FixTheIcon[Index]==0)
            {
                if(SetIcon%2==0)
                {
                    Seven.setText(Icon1);
                    Result[Index]=1;
                    SetIcon++;
                    // Time Active Player 1
                    State[0]=1;
                    State[1]=0;
                    StopWatch();
                    //
                    Check(Result);
                }
                else
                {
                    Seven.setText(Icon2);
                    Result[Index]=10;
                    SetIcon++;
                    // Time Active Player 2
                    State[0]=0;
                    State[1]=1;
                    StopWatch();
                    //
                    Check(Result);
                }
                FixTheIcon[Index]=1;
            }
        }
    }//GEN-LAST:event_SevenActionPerformed

    private void EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightActionPerformed
        // TODO add your handling code here:
        if(Disable==0)
        {
            int Index=7;
            if(FixTheIcon[Index]==0)
            {
                if(SetIcon%2==0)
                {
                    Eight.setText(Icon1);
                    Result[Index]=1;
                    SetIcon++;
                    // Time Active Player 1
                    State[0]=1;
                    State[1]=0;
                    StopWatch();
                    //
                    Check(Result);
                }
                else
                {
                    Eight.setText(Icon2);
                    Result[Index]=10;
                    SetIcon++;
                    // Time Active Player 2
                    State[0]=0;
                    State[1]=1;
                    StopWatch();
                    //
                    Check(Result);
                }
                FixTheIcon[Index]=1;
            }
        }
    }//GEN-LAST:event_EightActionPerformed

    private void NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineActionPerformed
        // TODO add your handling code here:
        if(Disable==0)
        {
            int Index=8;
            if(FixTheIcon[Index]==0)
            {
                if(SetIcon%2==0)
                {
                    Nine.setText(Icon1);
                    Result[Index]=1;
                    SetIcon++;
                    // Time Active Player 1
                    State[0]=1;
                    State[1]=0;
                    StopWatch();
                    //
                    Check(Result);
                }
                else
                {
                    Nine.setText(Icon2);
                    Result[Index]=10;
                    SetIcon++;
                    // Time Active Player 2
                    State[0]=0;
                    State[1]=1;
                    StopWatch();
                    //
                    Check(Result);
                }
                FixTheIcon[Index]=1;
            }
        }
    }//GEN-LAST:event_NineActionPerformed

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
        // TODO add your handling code here:
        
        HandlingStartStop=0;
        Disable=0;
        SetIcon=0;
        for(int i=0; i<=8; i++)
        {
            FixTheIcon[i]=0;
            Result[i]=0;
        }
        One.setText("");
        Two.setText("");
        Three.setText("");
        Four.setText("");
        Five.setText("");
        Six.setText("");
        Seven.setText("");
        Eight.setText("");
        Nine.setText("");
        ReultField.setText("");
        
        State[0] = 0;
        State[1] = 1;
        MillisecondP1.setText("00");
        SecondP1.setText("00");
        Milliseconds[0]=0;
        Seconds[0]=0;
        StopWatch();
        
        MillisecondP2.setText("00");
        SecondP2.setText("00");
        Milliseconds[1]=0;
        Seconds[1]=0;
        
    }//GEN-LAST:event_RestartActionPerformed

    private void Restart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restart1ActionPerformed
        // TODO add your handling code here:
        if(HandlingStartStop==1)
        {
            HandlingStartStop=0;
            
            Disable=0;
            State[0]=Container[0];
            State[1]=Container[1];
            StopWatch();
        }
    }//GEN-LAST:event_Restart1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(HandlingStartStop==0)
        {
            HandlingStartStop=1;
            
            Disable=1;
            Container[0]=State[0];
            Container[1]=State[1];
            State[0]=1;
            State[1]=1;
            StopWatch();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public String Icon1= new String();
    public String Icon2= new String();
    public String PlayerOneName=new String();
    public String PlayerTwoName=new String();
    public int SetIcon=0;
    public int[] FixTheIcon = new int[] {0,0,0,0,0,0,0,0,0};
    public int[] Result = new int[] {0,0,0,0,0,0,0,0,0};
    public int Disable=0;
    
    static int[] State = new int[] {0,1};
    static int[] Milliseconds = new int[] {0,0};
    static int[] Seconds = new int[] {0,0};
    
    int[] Container = new int[] {0,0}; // If i press Stop button that moment i have to store the "State" value.
    // Whenever i will press "Start" button and that time i will initialize with those values
    int HandlingStartStop=0;
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eight;
    public javax.swing.JTextField F2Player1Name;
    public javax.swing.JTextField F2Player2Name;
    private javax.swing.JButton Five;
    private javax.swing.JButton Four;
    private javax.swing.JTextField MillisecondP1;
    private javax.swing.JTextField MillisecondP2;
    private javax.swing.JButton Nine;
    private javax.swing.JButton One;
    private javax.swing.JButton Restart;
    private javax.swing.JButton Restart1;
    private javax.swing.JTextField ReultField;
    private javax.swing.JTextField SecondP1;
    private javax.swing.JTextField SecondP2;
    private javax.swing.JButton Seven;
    private javax.swing.JButton Six;
    private javax.swing.JButton Three;
    private javax.swing.JButton Two;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
